/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package com.alfredo.chatgptdebugger;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import org.openide.windows.TopComponent;


/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.alfredo.chatgptdebugger//ChatGPTWindow//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ChatGPTWindowTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = false)
@ActionID(category = "Window", id = "com.alfredo.chatgptdebugger.ChatGPTWindowTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ChatGPTWindowAction",
        preferredID = "ChatGPTWindowTopComponent"
)
@Messages({
    "CTL_ChatGPTWindowAction=ChatGPTWindow",
    "CTL_ChatGPTWindowTopComponent=ChatGPTWindow Window",
    "HINT_ChatGPTWindowTopComponent=This is a ChatGPTWindow window"
})
public final class ChatGPTWindowTopComponent extends TopComponent {

    private JTextArea inputArea;
    private JTextArea outputArea;
    private JButton sendButton;

    
    public ChatGPTWindowTopComponent() {
        initComponents();

        // === OUR CUSTOM UI ===
        setName("ChatGPT Assistant");
        setLayout(new BorderLayout());

        inputArea = new JTextArea(8, 80);
        inputArea.setLineWrap(true);
        inputArea.setWrapStyleWord(true);

        outputArea = new JTextArea(16, 80);
        outputArea.setEditable(false);
        outputArea.setLineWrap(true);
        outputArea.setWrapStyleWord(true);

        sendButton = new JButton("Send to ChatGPT");
        sendButton.addActionListener(e -> sendToChatGPT());

        JScrollPane inputScroll = new JScrollPane(inputArea);
        JScrollPane outputScroll = new JScrollPane(outputArea);

        JPanel topPanel = new JPanel(new BorderLayout());
        topPanel.add(new JLabel("Prompt / Error / Code:"), BorderLayout.NORTH);
        topPanel.add(inputScroll, BorderLayout.CENTER);
        topPanel.add(sendButton, BorderLayout.SOUTH);

        add(topPanel, BorderLayout.NORTH);
        add(outputScroll, BorderLayout.CENTER);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    private void sendToChatGPT() {
        String prompt = inputArea.getText().trim();
        if (prompt.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please write or paste code/error text before sending.");
            return;
        }

        outputArea.setText("Thinking...\n");

        new Thread(() -> {
            try {
                String answer = ChatGPTClient.askForDebugHelp(prompt);
                SwingUtilities.invokeLater(() -> outputArea.setText(answer));
            } catch (Exception ex) {
                SwingUtilities.invokeLater(() ->
                    outputArea.setText("Error calling ChatGPT:\n" + ex.getMessage())
                );
            }
        }).start();
    }

    public void appendFromEditor(String text) {
        if (text != null && !text.isEmpty()) {
            inputArea.append(text + "\n---\n");
        }
    }

    
}
